force-app/main/default/objects/Criteria__c/Criteria__c.object-meta.xml
<CustomObject>
    <label>Criteria</label>
    <nameField>
        <label>Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criterias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Criteria__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <description>APIname to compare</description>
    <label>FieldName</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Criteria__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Criteria__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <referenceTo>Segment__c</referenceTo>
    <relationshipLabel>Criterias</relationshipLabel>
    <relationshipName>Criterias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Criteria__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CriteriaController.cls
public with sharing class CriteriaController {
    public CriteriaController() {

        
    }

    @AuraEnabled(cacheable=true)
    public static List<Criteria__c> getCriterias(String segmentId) {
        List<Criteria__c> criterias = [SELECT Id, FieldName__c, Operation__c, Value__c FROM Criteria__c WHERE Segment__c =: segmentId];
        System.debug(criterias);
        return criterias;
    }
}